### ISSUE TITLE
Use of this lib with Esp8266

### ISSUE THREAD

**Issue by marksev1** [NicoHood/MSGEQ7#5]
Hi,.. I'd like to use your lib on a esp8266. Since esp has just one adc I would use just one msgeq7. Can I still input stereo signal and sample it as mono? Or just maybe buy a stereo to mono adapter? Also since there is just one ADC i would just look at one frequency for example some lower bass ones. Could you help me how to use your library for esp8266 pretty please.

**Comment by NicoHood** [comment]
ESP has a 1.8V ADC as far as I remember. Might be different. You can use a single MSGEQ7 at maximum, but you'd need to shift down the voltage. I have not idea if it works, but let me know of further information.

**Comment by marksev1** [comment]
Yeah the ADS is 1V so I'd have do make a voltage divider...What about from the coding perspecive could you guide me a bit on how to use it.

**Comment by NicoHood** [comment]
Just use it in mono mode and see if it compiles? The led example should work I think? any compile errors? Have you even tried it?

**Comment by NicoHood** [comment]
I just tried to compile the sketch and it seems to work. You just need a voltage divider and try it out. If it really does not work, come back and comment. And if it does, also come back and comment so we all know the result :) Thanks and good luck!

**Comment by marksev1** [comment]
Cool I will do so. :) With the example sketch. Next if I see that it works I have some sketch with neopixelbus library for animations and mqtt support is also inside, and I would like to put your library inside. So I'll gonna probably ask you a few questions then, since I'm a beginner.

**Comment by NicoHood** [comment]
Sure, but please do it via tox or PGP mail, so this issue tracker is not spammed.
www.contact.nicohood.de
